# Generated by Django 3.2.9 on 2021-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default='Empty Book')),
            ],
        ),
    ]
